COEFFS = {
    'health': 100,
    'weight': 100,
    'fame': 100,
    'holeDeep': 100,
    'wealth': 100,
    'respect': 100,
    'strength': 100,
    'agility': 100,
    'intelligence': 10,
    'charisma': 100,
    'actionPoints': 1,
    'diggingLevel': 1,
    'fightingLevel': 1,
    'tradingLevel': 1,
    'evasion': 100,
    'holdTurnsLeft': 1,
}

POSTFIXES = {
    'health': 'hp',
    'weight': 'kg',
    'fame': 'f',
    'holeDeep': 'm',
    'wealth': 'w',
    'respect': 'r',
    'strength': 'str',
    'agility': 'ag',
    'intelligence': 'int',
    'charisma': 'chr',
    'actionPoints': 'points',
    'diggingLevel': 'level',
    'fightingLevel': 'level',
    'tradingLevel': 'level',
    'evasion': 'ev',
    'holdTurnsLeft': 't'
}
