SMALL_DELAY = 0.1
MEDIUM_DELAY = 0.3
BIG_DELAY = 1

AFTER_SLEEP_ACTION_POINTS = 2

RESPECT_A_COEFF = 1
RESPECT_B_COEFF = 1

DIG_INTELLIGENCE_COEFF = 1
DIG_STRENGTH_COEFF = 1

LEVEL_DIGGING_COEFF = 1
LEVEL_FIGHTING_COEFF = 1
LEVEL_TRADING_COEFF = 1

DIGGING_FAILURE_CRIT_BOUND = 5
DIGGING_FAILURE_SIMPLE_BOUND = 14
DIGGING_SUCCESS_SIMPLE_BOUND = 24
DIGGING_NORMAL_DEEP = 0.1
DIGGING_WEIGHT_COST = 0.1

FLOOD_EVENT_FAILURE_CRIT_BOUND = 12
FLOOD_EVENT_FAILURE_SIMPLE_BOUND = 19
FLOOD_EVENT_SUCCESS_SIMPLE_BOUND = 30

FLOOD_EVENT_ESCAPE_COEFF = 10
FLOOD_EVENT_CRIT_HOLE_REDUCTION = 0.3
FLOOD_EVENT_SIMPLE_HOLE_REDUCTION = 0.3

DOWNFALL_EVENT_FAILURE_CRIT_BOUND = 12
DOWNFALL_EVENT_FAILURE_SIMPLE_BOUND = 19
DOWNFALL_EVENT_SUCCESS_SIMPLE_BOUND = 30

DOWNFALL_EVENT_ESCAPE_COEFF = 10
DOWNFALL_EVENT_CRIT_HOLE_REDUCTION = 0.3
DOWNFALL_EVENT_CRIT_GOPHER_DAMAGE = 0.3
DOWNFALL_EVENT_SIMPLE_GOPHER_DAMAGE = 0.05
DOWNFALL_EVENT_SIMPLE_HOLE_REDUCTION = 0.3
