AFTER_SLEEP_ACTION_POINTS = 2
RESPECT_A_COEFF = 1
RESPECT_B_COEFF = 1
DIG_INTELLIGENCE_COEFF = 1
DIG_STRENGTH_COEFF = 1
LEVEL_DIGGING_COEFF = 1
LEVEL_FIGHTING_COEFF = 1
LEVEL_TRADING_COEFF = 1

DIGGING_FAILURE_CRIT_BOUND = 5
DIGGING_FAILURE_SIMPLE_BOUND = 14
DIGGING_SUCCESS_SIMPLE_BOUND = 24
DIGGING_NORMAL_DEEP = 0.1
DIGGING_WEIGHT_COST = 0.1
